Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      RoleName: ${self:custom.config.project}-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ${self:custom.config.project}-ddb-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:DescribeTable"
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                  - "dynamodb:GetItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:DeleteItem"
                Resource:
                  - Fn::Join:
                      - ':'
                      - - 'arn:aws:dynamodb'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'table/${self:custom.config.project}-author-table-${self:custom.stage}'
                  - Fn::Join:
                      - ':'
                      - - 'arn:aws:dynamodb'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'table/${self:custom.config.project}-book-table-${self:custom.stage}'

        - PolicyName: ${self:custom.config.project}-ddb-index-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:DescribeTable"
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                  - "dynamodb:GetItem"
                Resource:
                  - Fn::Join:
                      - ':'
                      - - 'arn:aws:dynamodb'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'table/${self:custom.config.project}-book-table-${self:custom.stage}/index/authorId-index'

        - PolicyName: ${self:custom.config.project}-log-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogStreams"
                Resource:
                          - "arn:aws:logs:*:*:*"
